# Generated by Django 4.0.3 on 2022-04-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=140)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('show', models.BooleanField(default=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Image')),
                ('o_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default='0')),
                ('relays', models.IntegerField(default='0')),
                ('comments', models.IntegerField(default='0')),
                ('fans', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Mlikes',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.message', verbose_name='messageID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.message', verbose_name='messageID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.message', verbose_name='messageID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Cikes',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.comment', verbose_name='commentID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('back', models.CharField(default='white', max_length=50)),
                ('music', models.FileField(blank=True, null=True, upload_to='')),
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('Font_color', models.CharField(default='black', max_length=50)),
                ('Border_color', models.CharField(default='white', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username')),
            ],
        ),
    ]
