# Generated by Django 4.0.3 on 2022-04-30 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_message_user_introduction_user_profilephoto_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='blogger.message', verbose_name='messageID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm', to='blogger.message', verbose_name='messageID'),
        ),
        migrations.AlterField(
            model_name='mlikes',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml', to='blogger.message', verbose_name='messageID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nt', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='username'),
        ),
    ]
